# Site settings
title: "jekyll Resume Template"
description: "I want to be a Robotic Engineer because i like working with robots and using code to make them move.Also when i watch tv shows about it they are able to make them do some cool things which is very interesting to me"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Jamarc Hurd"
resume_title:                   "Student at Campbell Highschool"
resume_contact_email:
  "Jdh218@icloud.com"
resume_header_contact_info: "123 Sesame Street | 770-568-7206 | jdh218@icloud.com"
resume_header_intro: "<p>"I want to be a Robotic Engineer because i like working with robots and using code to make them move.Also when i watch tv shows about it they are able to make them do some cool things which is very interesting to me."

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "no"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/jglovier/resume-template"
  resume_twitter_url:           "http://twitter.com/jglovier"
  resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://joelglovier.com"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
